### ISSUE TITLE
Query on particular assignment group

### ISSUE THREAD

**Issue by fartbagxp** [rbw/snow#48]
I can't get any results using a query against a particular assignment group.
It returns nothing, and I'm wondering if I have to create an Assignment Group schema created.

I have a simple schema.
```
class Incident(Schema):
  __location__ = "/api/now/table/incident"

  sys_id = fields.Text(is_primary=True)
  sys_created_by = fields.Text()
  sys_created_on = fields.Datetime()
  number = fields.Text()
  incident_state = fields.Text()
  state = fields.Text()
  short_description = fields.Text()
  description = fields.Text()
  assignment_group = fields.Text(pluck=Joined.DISPLAY_VALUE)
  assigned_to = fields.Text()
  opened_at = fields.Datetime()
  closed_at = fields.Text()
  sys_updated_on = fields.Datetime()
  closed_by = fields.Text()
  active = fields.Text()

async with self.app.resource(Incident) as r:
  selection = select(
    Incident.assignment_group.equals("Service Desk")
  ).order_desc(Incident.number)

  async for item in r.stream(selection, limit=0, chunk_size=250):
    print(item)
```

I spun up a ServiceNow test instance and this assignment group seems like a common group.
![image](https://user-images.githubusercontent.com/8839850/79503503-42a94900-7fff-11ea-87b2-1ff0e58c0cef.png)

I tried with datetime query selection and those are working, just not the one for assignment group.

Any help is much appreciated.

**Comment by rbw** [comment]
> It returns nothing, and I'm wondering if I have to create an Assignment Group schema created.

Yes, I'm aware of this. Relations are queried by *sys_id* if not using a `PartialSchema`. While this is not a bug, I do agree automatically querying by *name* in this case would be more natural.

Currently, if you want to query by name, you can use a `PartialSchema`:
```python
class AssignmentGroup(PartialSchema):
    sys_id = fields.Text()
    name = fields.Text()

class Incident(Schema):
    __location__ = "/api/now/table/incident"

    number = fields.Text()
    assignment_group = AssignmentGroup

selection = select(
    Incident.assignment_group.name.equals("Service Desk")
).order_desc(Incident.number)
```

Building support for querying by a related table's field without using `PartialSchema` shouldn't be too hard.

What's your take on something like this?:

```python
assignment_group = fields.Text(pluck=Joined.DISPLAY_VALUE, query_by="assignment_group.name")
```

...or perhaps always use related table's *name* when plucking *display value*. That'd be somewhat inflexible and implicit though. Hmm.. need to do some pondering on this.

**Comment by fartbagxp** [comment]
Ahh, I didn't know the existence of `PartialSchema`.
The following is clear to me, provided that I use a `PartialSchema`.
```
selection = select(
    Incident.assignment_group.name.equals("Service Desk")
).order_desc(Incident.number)
```

I prefer not having something like query_by - it feels like a bit of a hack to put that in, but may be useful in some other cases.
This might be more of an example / nudge of how the users is intended to use the library. I much prefer the `Incident.assignment_group.name.equals("Service Desk")`.

Thank you!

**Comment by rbw** [comment]
No problem.

It's covered in the documentation here: https://python-snow.readthedocs.io/en/latest/reference/resource/schema.html#nesting
